#!/usr/bin/env python3
"""
Execute waypoints generated by Cosmos 8B evaluation and record a new trace.

Reads the `recommended_waypoints` array from a Cosmos 8B output JSON file,
validates joint values, and executes them on the UR5e via MoveIt while
recording joint states for subsequent re-evaluation.

Usage
-----
    python3 tests/execute_cosmos_waypoints.py outputs/cosmos/8b/cosmos_screw_<id>_<ts>.json
    python3 tests/execute_cosmos_waypoints.py outputs/cosmos/8b/cosmos_screw_<id>_<ts>.json --dry-run

Prerequisites
-------------
    Terminal 1:  ros2 launch ur5e_robotiq_moveit_config bringup.launch.py
    Terminal 2:  python3 tests/execute_cosmos_waypoints.py <cosmos_output.json>
"""

import argparse
import json
import math
import re
import sys
import threading
import time
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "src" / "robot_agent"))

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
GRIPPER_LINKS = [
    'tool0',
    'rq_robotiq_85_base_link',
    'rq_robotiq_85_left_knuckle_link',
    'rq_robotiq_85_right_knuckle_link',
    'rq_robotiq_85_left_finger_link',
    'rq_robotiq_85_right_finger_link',
    'rq_robotiq_85_left_inner_knuckle_link',
    'rq_robotiq_85_right_inner_knuckle_link',
    'rq_robotiq_85_left_finger_tip_link',
    'rq_robotiq_85_right_finger_tip_link',
]

# UR5e joint limits
JOINT_LIMITS = [
    (-2 * math.pi, 2 * math.pi),   # shoulder_pan
    (-2 * math.pi, 2 * math.pi),   # shoulder_lift
    (-math.pi, math.pi),           # elbow
    (-2 * math.pi, 2 * math.pi),   # wrist_1
    (-2 * math.pi, 2 * math.pi),   # wrist_2
    (-2 * math.pi, 2 * math.pi),   # wrist_3
]

# Phases that trigger gripper/collision actions
GRIPPER_OPEN_PHASES = {"open_gripper"}
GRIPPER_CLOSE_PHASES = {"close_gripper"}
COLLISION_ALLOW_PHASES = {"approach_screwdriver"}
ATTACH_PHASES = {"close_gripper"}
DETACH_PHASES = {"open_gripper_drop"}

# ---------------------------------------------------------------------------
# Pick geometry — same as test_screw_continuous.py
# Uses Cartesian IK so the robot always finds a valid pick solution.
# ---------------------------------------------------------------------------
SCREWDRIVER_X      = 0.45
SCREWDRIVER_Y      = 0.00
SCREWDRIVER_RADIUS = 0.012
FINGER_TIP_OFFSET  = 0.170
SCREWDRIVER_MID_Z  = 0.09
GRASP_Z    = SCREWDRIVER_MID_Z + FINGER_TIP_OFFSET   # 0.26 m
APPROACH_H = 0.18
RETREAT_H  = 0.20
GRASP_QX, GRASP_QY, GRASP_QZ, GRASP_QW = 1.0, 0.0, 0.0, 0.0
GRASP_GRIPPER_POSITION = 0.57
HOME_JOINTS = [0.0, -math.pi / 2, 0.0, -math.pi / 2, 0.0, 0.0]
PICK_SEED   = [0.0, -1.7, 1.8, -1.7, -math.pi / 2, 0.0]

# Phases that belong to the pick sequence — executed via Cartesian IK
PICK_PHASES = {"home", "approach_screwdriver", "descend_to_grasp",
               "close_gripper", "retreat_upward"}


# ---------------------------------------------------------------------------
# Waypoint extraction
# ---------------------------------------------------------------------------

def repair_json(raw: str) -> str:
    """Attempt to repair truncated JSON from LLM output."""
    # Fix unescaped newlines inside string values
    raw = re.sub(r'("note"\s*:\s*"[^"]*)\n\s*', r'\1 ', raw)

    # Try parsing as-is first
    try:
        json.loads(raw)
        return raw
    except json.JSONDecodeError:
        pass

    # Try closing unclosed brackets/braces
    # Remove trailing incomplete object (partial waypoint)
    # Find last complete waypoint (ends with "}")
    last_brace = raw.rfind("}")
    if last_brace == -1:
        return raw

    # Check if we need to close the array and outer object
    trimmed = raw[:last_brace + 1]

    # Count open/close brackets to figure out what's missing
    opens = trimmed.count("[") - trimmed.count("]")
    braces = trimmed.count("{") - trimmed.count("}")

    suffix = "]" * opens + "}" * braces
    repaired = trimmed + suffix

    try:
        json.loads(repaired)
        return repaired
    except json.JSONDecodeError:
        pass

    return raw


def extract_waypoints(cosmos_json_path: Path) -> list[dict]:
    """Extract recommended_waypoints from a Cosmos output JSON file.

    Checks top-level ``recommended_waypoints`` first (written by
    run_8b_pipeline.py with pick + screwing merged).  Falls back to
    parsing the raw ``response`` text from the LLM.
    """
    with open(cosmos_json_path) as f:
        meta = json.load(f)

    # Prefer the pre-merged top-level array (includes pick + screwing)
    if isinstance(meta.get("recommended_waypoints"), list) and meta["recommended_waypoints"]:
        return meta["recommended_waypoints"]

    response_text = meta.get("response", "")

    # Strip markdown code fences if present
    json_match = re.search(r'```(?:json)?\s*(\{.*?\})\s*```', response_text, re.DOTALL)
    if json_match:
        inner = json_match.group(1)
    else:
        # Find the outermost JSON object
        brace_match = re.search(r'\{', response_text)
        if brace_match:
            inner = response_text[brace_match.start():]
        else:
            inner = response_text

    # Attempt repair for truncated/malformed JSON
    inner = repair_json(inner)

    try:
        parsed = json.loads(inner)
    except json.JSONDecodeError as e:
        print(f"ERROR: Could not parse JSON from response (even after repair): {e}")
        print(f"Response preview: {response_text[:500]}")
        sys.exit(1)

    waypoints = parsed.get("recommended_waypoints", [])
    if not waypoints:
        print("ERROR: No recommended_waypoints found in the Cosmos output.")
        print("Available keys:", list(parsed.keys()))
        sys.exit(1)

    return waypoints


def validate_waypoints(waypoints: list[dict]) -> list[str]:
    """Validate waypoint joint values against UR5e limits. Returns list of errors."""
    errors = []
    for i, wp in enumerate(waypoints):
        phase = wp.get("phase", f"waypoint_{i}")

        # Check joints array
        joints = wp.get("joints")
        if not joints or not isinstance(joints, list) or len(joints) != 6:
            errors.append(f"[{i}] {phase}: joints must be a list of 6 values, got {joints}")
            continue

        for j, (val, (lo, hi)) in enumerate(zip(joints, JOINT_LIMITS)):
            if not isinstance(val, (int, float)):
                errors.append(f"[{i}] {phase}: joint {j} is not a number: {val}")
            elif val < lo or val > hi:
                errors.append(f"[{i}] {phase}: joint {j} = {val:.4f} out of range [{lo:.4f}, {hi:.4f}]")

        # Check gripper
        gripper = wp.get("gripper")
        if gripper is not None and not isinstance(gripper, (int, float)):
            errors.append(f"[{i}] {phase}: gripper is not a number: {gripper}")

        # Check velocity_scaling
        vs = wp.get("velocity_scaling")
        if vs is not None:
            if not isinstance(vs, (int, float)) or vs <= 0 or vs > 1.0:
                errors.append(f"[{i}] {phase}: velocity_scaling must be (0, 1.0], got {vs}")

    return errors


# ---------------------------------------------------------------------------
# Trace saving
# ---------------------------------------------------------------------------

def save_trace(trace) -> Path:
    out_dir = Path(__file__).parent.parent / "outputs" / "screw_trace"
    out_dir.mkdir(parents=True, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    path = out_dir / f"cosmos_executed_{ts}.json"
    data = {
        "trace_id":       trace.trace_id,
        "label":          trace.label,
        "duration_sec":   round(trace.duration_sec, 4),
        "num_snapshots":  len(trace.snapshots),
        "snapshots": [
            {
                "timestamp":   round(s.timestamp, 6),
                "joint_names": s.joint_names,
                "positions":   [round(v, 6) for v in s.positions],
                "velocities":  [round(v, 6) for v in s.velocities],
            }
            for s in trace.snapshots
        ],
    }
    path.write_text(json.dumps(data, indent=2))
    return path


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def make_pose(x, y, z, qx, qy, qz, qw):
    from geometry_msgs.msg import Pose
    p = Pose()
    p.position.x, p.position.y, p.position.z = x, y, z
    p.orientation.x, p.orientation.y = qx, qy
    p.orientation.z, p.orientation.w = qz, qw
    return p


# Mutable holder for the last successful IK joints (used as seed for next IK)
_last_joints = [None]


def ik_and_move(moveit, pose, velocity_scaling=0.3, seeds=None):
    """Try each IK seed in order; store successful joints in _last_joints."""
    for seed in (seeds or [None]):
        joints = moveit.ik(pose, seed_joints=seed)
        if joints is not None:
            ok = moveit.plan_and_execute_joints(joints, velocity_scaling=velocity_scaling)
            if ok:
                _last_joints[0] = list(joints)
            return ok
    return False


def wait_for_joint_states(node, timeout_sec=20.0):
    from sensor_msgs.msg import JointState
    received = threading.Event()
    sub = node.create_subscription(JointState, "/joint_states", lambda _: received.set(), 10)
    ok = received.wait(timeout_sec)
    node.destroy_subscription(sub)
    return ok


def make_node():
    from rclpy.node import Node
    class CosmosWaypointNode(Node):
        def __init__(self):
            super().__init__("cosmos_waypoint_executor")
    return CosmosWaypointNode()


# ---------------------------------------------------------------------------
# Main execution
# ---------------------------------------------------------------------------

def execute_waypoints(waypoints: list[dict], dry_run: bool = False):
    """Execute the waypoint sequence on the robot.

    Pick phases (home, approach_screwdriver, descend_to_grasp, close_gripper,
    retreat_upward) are executed using Cartesian IK — same proven approach as
    test_screw_continuous.py.  All other phases use the joint values from the
    waypoint file directly.
    """
    if dry_run:
        print("\n=== DRY RUN — validating only, no robot motion ===\n")
        for i, wp in enumerate(waypoints):
            phase = wp.get("phase", "?")
            phase_key = phase.lower().replace(" ", "_")
            joints = wp.get("joints", [])
            gripper = wp.get("gripper", "?")
            vs = wp.get("velocity_scaling", 0.3)
            note = wp.get("note", "")
            mode = "IK" if phase_key in PICK_PHASES else "JOINT"
            print(f"  [{i+1:2d}] {phase:<25} [{mode:>5}]  gripper={gripper}  vs={vs}  "
                  f"j=[{', '.join(f'{j:.3f}' for j in joints)}]")
            if note:
                print(f"       {note}")
        print(f"\n  Total: {len(waypoints)} waypoints — validation passed.\n")
        return

    import rclpy
    from rclpy.executors import MultiThreadedExecutor
    from sensor_msgs.msg import JointState
    from robot_agent.moveit_client import MoveItClient
    from robot_agent.gripper_client import GripperClient
    from robot_agent.recorder.joint_recorder import JointStateRecorder

    rclpy.init()
    node = make_node()
    executor = MultiThreadedExecutor(num_threads=4)
    executor.add_node(node)
    spin_thread = threading.Thread(target=executor.spin, daemon=True)
    spin_thread.start()

    try:
        node.get_logger().info("Waiting for /joint_states ...")
        if not wait_for_joint_states(node):
            node.get_logger().error("No /joint_states — is bringup running?")
            return

        moveit = MoveItClient(node)
        gripper_client = GripperClient(node)

        # Set up joint-state recorder
        recorder = JointStateRecorder(node)
        node.create_subscription(
            JointState, "/joint_states", recorder.on_joint_state, 10
        )
        node.get_logger().info("MoveIt + gripper + recorder ready.")

        # ── Pre-compute Cartesian poses for the pick sequence ──
        approach_pose = make_pose(
            SCREWDRIVER_X, SCREWDRIVER_Y, GRASP_Z + APPROACH_H,
            GRASP_QX, GRASP_QY, GRASP_QZ, GRASP_QW,
        )
        grasp_pose = make_pose(
            SCREWDRIVER_X, SCREWDRIVER_Y, GRASP_Z,
            GRASP_QX, GRASP_QY, GRASP_QZ, GRASP_QW,
        )
        retreat_pose = make_pose(
            SCREWDRIVER_X, SCREWDRIVER_Y, GRASP_Z + RETREAT_H,
            GRASP_QX, GRASP_QY, GRASP_QZ, GRASP_QW,
        )

        _last_joints[0] = list(PICK_SEED)

        print("\n" + "=" * 66)
        print("  Cosmos Waypoint Execution")
        print(f"  Waypoints: {len(waypoints)}")
        print("=" * 66)

        recorder.start_recording("cosmos_waypoint_execution")
        prev_gripper = None
        screwdriver_attached = False

        all_ok = True
        for i, wp in enumerate(waypoints):
            phase = wp.get("phase", f"step_{i}")
            phase_key = phase.lower().replace(" ", "_")
            joints = wp["joints"]
            gripper_val = wp.get("gripper")
            vs = wp.get("velocity_scaling", 0.3)
            note = wp.get("note", "")

            print(f"\n[{i+1:2d}/{len(waypoints)}] {phase}")
            if note:
                print(f"         {note}")

            t0 = time.monotonic()

            # ==============================================================
            # PICK PHASES — Cartesian IK (same as test_screw_continuous.py)
            # ==============================================================
            if phase_key == "home":
                ok = moveit.plan_and_execute_joints(HOME_JOINTS, velocity_scaling=vs)
                elapsed = time.monotonic() - t0
                print(f"         → home (joint) {'OK' if ok else 'FAILED'}  ({elapsed:.2f}s)")
                if not ok:
                    all_ok = False
                    break
                prev_gripper = gripper_val
                time.sleep(0.3)
                continue

            if phase_key == "approach_screwdriver":
                # Open gripper first
                gripper_client.open()
                prev_gripper = 0.0
                # Allow collision with screwdriver
                moveit.allow_collision("screwdriver")
                print("         → collision allowed with screwdriver")
                # IK approach
                ok = ik_and_move(moveit, approach_pose, vs, [PICK_SEED, HOME_JOINTS])
                elapsed = time.monotonic() - t0
                print(f"         → approach (IK) {'OK' if ok else 'FAILED'}  ({elapsed:.2f}s)")
                if not ok:
                    all_ok = False
                    break
                time.sleep(0.3)
                continue

            if phase_key == "descend_to_grasp":
                ok = ik_and_move(moveit, grasp_pose, vs, [_last_joints[0], PICK_SEED])
                elapsed = time.monotonic() - t0
                print(f"         → descend (IK) {'OK' if ok else 'FAILED'}  ({elapsed:.2f}s)")
                if not ok:
                    all_ok = False
                    break
                prev_gripper = 0.0
                time.sleep(0.3)
                continue

            if phase_key == "close_gripper":
                grip_pos = gripper_val if gripper_val and gripper_val > 0 else GRASP_GRIPPER_POSITION
                ok = gripper_client.set_position(grip_pos)
                prev_gripper = grip_pos
                elapsed = time.monotonic() - t0
                print(f"         → gripper close ({grip_pos:.2f}) {'OK' if ok else 'FAILED'}  ({elapsed:.2f}s)")
                if not ok:
                    all_ok = False
                    break
                # Attach screwdriver after closing gripper
                if not screwdriver_attached:
                    moveit.attach_object("screwdriver", "tool0", touch_links=GRIPPER_LINKS)
                    screwdriver_attached = True
                    print("         → screwdriver attached to tool0")
                time.sleep(0.3)
                continue

            if phase_key == "retreat_upward":
                ok = ik_and_move(moveit, retreat_pose, vs,
                                 [_last_joints[0], PICK_SEED, HOME_JOINTS])
                elapsed = time.monotonic() - t0
                print(f"         → retreat (IK) {'OK' if ok else 'FAILED'}  ({elapsed:.2f}s)")
                if not ok:
                    all_ok = False
                    break
                prev_gripper = gripper_val
                time.sleep(0.3)
                continue

            # ==============================================================
            # NON-PICK PHASES — use joint values from the waypoint file
            # ==============================================================

            # Return home — always use known HOME_JOINTS
            if phase_key == "return_home":
                ok = moveit.plan_and_execute_joints(HOME_JOINTS, velocity_scaling=vs)
                elapsed = time.monotonic() - t0
                print(f"         → return home (joint) {'OK' if ok else 'FAILED'}  ({elapsed:.2f}s)")
                if not ok:
                    all_ok = False
                    break
                prev_gripper = gripper_val
                time.sleep(0.3)
                continue

            # Gripper-only open phase — return screwdriver to holder first
            if phase_key in GRIPPER_OPEN_PHASES:
                if screwdriver_attached:
                    ok = ik_and_move(moveit, approach_pose, 0.3,
                                     [_last_joints[0], PICK_SEED, HOME_JOINTS])
                    print(f"         → holder approach {'OK' if ok else 'FAILED'}")
                    if ok:
                        ok = ik_and_move(moveit, grasp_pose, 0.2,
                                         [_last_joints[0], PICK_SEED])
                        print(f"         → lower to holder {'OK' if ok else 'FAILED'}")
                ok = gripper_client.open()
                prev_gripper = 0.0
                elapsed = time.monotonic() - t0
                print(f"         → gripper open {'OK' if ok else 'FAILED'}  ({elapsed:.2f}s)")
                if not ok:
                    all_ok = False
                    break
                if screwdriver_attached:
                    moveit.detach_object("screwdriver")
                    screwdriver_attached = False
                    print("         → screwdriver detached")
                    ik_and_move(moveit, retreat_pose, 0.3,
                                [_last_joints[0], PICK_SEED, HOME_JOINTS])
                    print("         → retreated from holder")
                time.sleep(0.3)
                continue

            # Arm motion (model-generated screwing waypoints)
            ok = moveit.plan_and_execute_joints(joints, velocity_scaling=vs)
            elapsed = time.monotonic() - t0
            print(f"         → {'OK' if ok else 'FAILED'}  ({elapsed:.2f}s)")

            if not ok:
                all_ok = False
                print("         Aborting sequence.")
                break

            # Handle gripper changes after arm motion
            if gripper_val is not None and prev_gripper is not None:
                if abs(gripper_val - prev_gripper) > 0.05:
                    if gripper_val < 0.1:
                        gripper_client.open()
                        prev_gripper = 0.0
                        print("         → gripper opened")
                    else:
                        gripper_client.set_position(gripper_val)
                        prev_gripper = gripper_val
                        print(f"         → gripper set to {gripper_val:.2f}")

            if gripper_val is not None:
                prev_gripper = gripper_val

            time.sleep(0.3)

        # ── Stop recording and save trace ──
        trace = recorder.stop_recording()
        if trace and trace.snapshots:
            out_path = save_trace(trace)
            print(f"\n  Joint trace saved → {out_path}")
            print(f"  ({len(trace.snapshots)} snapshots, {trace.duration_sec:.2f}s)")
        else:
            print("\n  WARNING: no trace snapshots recorded.")

        print("\n" + "=" * 66)
        print(f"  Result: {'SUCCESS' if all_ok else 'FAILED — see above.'}")
        print("=" * 66 + "\n")

    except KeyboardInterrupt:
        print("\nInterrupted.")
    finally:
        executor.shutdown()
        node.destroy_node()
        rclpy.shutdown()


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Execute Cosmos-generated waypoints on UR5e and record trace"
    )
    parser.add_argument(
        "cosmos_output",
        help="Path to Cosmos 8B output JSON file (e.g., outputs/cosmos/8b/cosmos_screw_*.json)"
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Validate waypoints and print execution plan without moving the robot"
    )
    args = parser.parse_args()

    cosmos_path = Path(args.cosmos_output)
    if not cosmos_path.exists():
        print(f"ERROR: File not found: {cosmos_path}")
        sys.exit(1)

    print(f"\n[1] Loading Cosmos output: {cosmos_path.name}")
    waypoints = extract_waypoints(cosmos_path)
    print(f"    Found {len(waypoints)} waypoints")

    # Print phase summary
    phases = [wp.get("phase", "?") for wp in waypoints]
    print(f"    Phases: {' → '.join(phases)}")

    print(f"\n[2] Validating waypoints...")
    errors = validate_waypoints(waypoints)
    if errors:
        print("    Validation errors:")
        for e in errors:
            print(f"      {e}")
        sys.exit(1)
    print("    All waypoints valid.")

    print(f"\n[3] {'Dry run' if args.dry_run else 'Executing'}...")
    execute_waypoints(waypoints, dry_run=args.dry_run)


if __name__ == "__main__":
    main()
